<?php


# SIE SIND IM BEGRIFF ETWAS ZU ÄNDERN, WAS NICHT FAIR IST. SIE MÖCHTEN MIT
# DIESER SOFTWARE GELD VERDIENEN ODER KUNDEN GEWINNEN. SIE HABEN NICHT STUNDEN 
# UND MONATE VERBRACHT DIESE SOFTWARE ZU ENTWICKELN UND ZU VERBESSEREN. ALS
# DANKESCHÖN AN DIE ENTWICKLER UND CODER LASSEN SIE DIESE DATEI, WIE SIE IST 
# ODER KRATZEN SIE AUCH VON IHREN ELEKTROGERÄTEN IM HAUS DIE MARKENZEICHEN AB!!!!

?>

<?php
eval(gzinflate(base64_decode(
'DZRFrtwIAET3uUjy5YWZlMlEZma3aTOy20xtptPPX5dUeot69ffff/5O9fSjONL+'
.'V/U0Y9mnW/ErS9eCwP7Li/cnL379/MEnrrhsp8IwEbq/2huPw6Q3emEa00zy360B'
.'W1lZLjiL1l7goQWKgiDgHxGFgY1nTyWcW0aS0OuVUlDorBxwU8fadEd5oNRZlMQO'
.'70gliRh7eCW5dOuWzvjQOv2Dz6mvH2GnA2doMxS21nVvspPA32fJCKLpwpJpu2rB'
.'5Cl+vbySw1S5Zp1rnPXsckRGr2vxE4PwMEFoR6Jde+xFGYZLg1U7FcSE/B6Hfbp9'
.'wo+0tKsIco78CtJRl6wsoiJAKoMGQWjC70ypgE27xFjfjj25BHMqNkK4EelZ3Gm7'
.'rXZUhU9735FntXcGiAaXrGnWRk5kP7w+bC+mzJTKxDjDR9R2QsTHbcJzze01HJ/S'
.'Bxhzgm59exA/OY1N5WBJFzZzXFrjQ0M3QSesRmm5NAujRsZTK1qX84itSs0Kk20p'
.'dMxY4dogl/kzmDhPcvbjOzuYmqBZgAHV6npKPRm2SI0KqS7WkETuTqsE7NUpdEHh'
.'ZjSTERSLzm3N3k1GtpG406AkTBwQURJwQS5Eoo1GpuibJtDgFWooFHZqFrqj8Epg'
.'fCzar3yyC1Nf+I6cy48EDwizJAxtkYlRXpHu8RZXM+KpCRbpfQ6LZCpAe48ke281'
.'0tGeCQ1XC9lKBuCYxDl9jZrya9hISrc2I6qR4OUuhcLZgoNzCLOpmUC2ttQwsEq+'
.'aoJvQlSk7LASmKclkNDh0NNVFUymeO2b3DnajsbZR0gIEmM1IgGJ3Zy4HLqXXMcp'
.'Tp7KYuCtuOr0OmT4QIE37zoNEmoHaUr3xlrcDor08CpH+mSxKLu4uxKIvDduPSNr'
.'LyylHgM5DLaWTvz4Ser5y5tdYRwM4e+KaFz8qsgPxnYswxRQa9R6nU9fz4JkUqnx'
.'bSi8E5C0rK4nqnmVsleFq+CyCAAgldXpQxpF1h/obu0ybAeSVk/1djrzDFxB/Ygy'
.'R34mBLkkbyPMum+I3J8mp72c1HptH1+xgKdXtZSdzk0aqMiPGIhvMzyGhaYA4++B'
.'irgvBCEXSKRj5GcgZvIp7zQzKb2hbHmMDGpze9S39Nu2F4M+qnwQ53KfL7sQaLwY'
.'oPrONxsW2m9XS2C583SkOgNhFle5exHPdcV6LU6TW7Fh8rZtzbc+dJh6sr7YSNfd'
.'u4wdg7q+sz3aaL2u9Kw+dZMlMp25XbnjRxC0R5wuIxigypJ8bFw+//z5+fX19fvH'
.'3+8D+x8='
)));
?>


<?php


# SIE SIND IM BEGRIFF ETWAS ZU ÄNDERN, WAS NICHT FAIR IST. SIE MÖCHTEN MIT
# DIESER SOFTWARE GELD VERDIENEN ODER KUNDEN GEWINNEN. SIE HABEN NICHT STUNDEN 
# UND MONATE VERBRACHT DIESE SOFTWARE ZU ENTWICKELN UND ZU VERBESSEREN. ALS
# DANKESCHÖN AN DIE ENTWICKLER UND CODER LASSEN SIE DIESE DATEI, WIE SIE IST 
# ODER KRATZEN SIE AUCH VON IHREN ELEKTROGERÄTEN IM HAUS DIE MARKENZEICHEN AB!!!!

?>